# Generated by Django 4.2.5 on 2023-09-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bancada', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manutencoes',
            new_name='Manutencao',
        ),
    ]
