# Generated by Django 4.2.5 on 2023-09-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bancada', '0002_rename_manutencoes_manutencao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='idade',
            new_name='tell',
        ),
    ]
