# Generated by Django 4.2.5 on 2023-09-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_bancada', '0003_rename_idade_manutencao_tell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='id_manucencao',
            new_name='id_manutencao',
        ),
    ]
